---

- name: Include vaulted vars
  include_vars: vault.yml

- name: Start {{ web_app }} web app
  azure_rm_webapp:
    subscription_id: "{{ az_subscription_id }}"
    tenant: "{{ az_tenant }}"
    client_id: "{{ az_client_id }}"
    secret: "{{ az_secret }}" 
    resource_group: "infra-demo"
    name: "{{ web_app }}"
    app_state: started
